### ISSUE TITLE
Build fails on Linux because of missing system libraries

### ISSUE THREAD

**Issue by eyalroz** [hannesmuehleisen/sqlite-simplified#1]
If I clone and `make`, on my GNU/Linux Mint 18.3, I get:

```
cc  alter.lo analyze.lo attach.lo auth.lo backup.lo bitvec.lo btmutex.lo btree.lo build.lo callback.lo complete.lo ctime.lo date.lo dbpage.lo dbstat.lo delete.lo expr.lo fault.lo fkey.lo func.lo global.lo hash.lo insert.lo legacy.lo loadext.lo main.lo malloc.lo mem0.lo mem1.lo mem2.lo mem3.lo mem5.lo memjournal.lo mutex.lo mutex_noop.lo mutex_unix.lo mutex_w32.lo notify.lo opcodes.lo os.lo os_unix.lo os_win.lo pager.lo parse.lo pcache.lo pcache1.lo pragma.lo prepare.lo printf.lo random.lo resolve.lo rowset.lo select.lo status.lo table.lo threads.lo tokenize.lo treeview.lo trigger.lo update.lo util.lo vacuum.lo vdbe.lo vdbeapi.lo vdbeaux.lo vdbeblob.lo vdbemem.lo vdbesort.lo vdbetrace.lo wal.lo walker.lo where.lo wherecode.lo whereexpr.lo utf.lo vtab.lo shell.lo -o sqlite
mutex_unix.lo: In function `pthreadMutexTry':
/home/eyalroz/src/sqlite-simplified/mutex_unix.c:325: undefined reference to `pthread_mutex_trylock'
mutex_unix.lo: In function `pthreadMutexAlloc':
/home/eyalroz/src/sqlite-simplified/mutex_unix.c:180: undefined reference to `pthread_mutexattr_init'
/home/eyalroz/src/sqlite-simplified/mutex_unix.c:181: undefined reference to `pthread_mutexattr_settype'
/home/eyalroz/src/sqlite-simplified/mutex_unix.c:183: undefined reference to `pthread_mutexattr_destroy'
os_unix.lo: In function `unixDlError':
/home/eyalroz/src/sqlite-simplified/os_unix.c:6252: undefined reference to `dlerror'
os_unix.lo: In function `unixDlClose':
/home/eyalroz/src/sqlite-simplified/os_unix.c:6283: undefined reference to `dlclose'
os_unix.lo: In function `unixDlSym':
/home/eyalroz/src/sqlite-simplified/os_unix.c:6279: undefined reference to `dlsym'
os_unix.lo: In function `unixDlOpen':
/home/eyalroz/src/sqlite-simplified/os_unix.c:6238: undefined reference to `dlopen'
threads.lo: In function `sqlite3ThreadCreate':
/home/eyalroz/src/sqlite-simplified/threads.c:77: undefined reference to `pthread_create'
threads.lo: In function `sqlite3ThreadJoin':
/home/eyalroz/src/sqlite-simplified/threads.c:97: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'sqlite' failed
make: *** [sqlite] Error 1
```
On (most) Linux systems, you would need to link with `-ldl -lpthread`. But - in order to decide you need those flags, you need a slightly more involved build mechanism.

**Comment by hannes** [comment]
Fixed, thanks

**Comment by eyalroz** [comment]
No, not fixed... 

**Edit:** Sorry, the earlier version of this comment is wrong. It's actually a linker command-line argument issue. I'll explain with a PR.
